//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kachalka1.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListEx
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Xp { get; set; }
    
        public virtual Type Type { get; set; }
    }
}
